version: "3.9"

services:
  app:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app  # Enable live code reload
    environment:
      FLASK_ENV: development
    command: python app.py  # Use Flask's built-in server in dev
    profiles: ["dev"]

  app-prod:
    build: .
    ports:
      - "5003:5003"
    environment:
      FLASK_ENV: production
    command: gunicorn -w 4 -b 0.0.0.0:5003 app:app
    profiles: ["prod"]
